dist: bionic

env:
- TEST_WITH_NETWORK=1

language: perl
perl:
    - "5.30"
    - "5.28"
    - "5.26"
    - "5.24"
    - "5.22"
    - "5.16"

before_install:
      # quoting preserves newlines in the script and then avoid error if the
      # script contains comments
    - eval "$(curl https://travis-perl.github.io/init)"
    - sudo apt-get install -y libidn11-dev
    - cpan-install --deps Devel::CheckLib Module::Install Module::Install::XSUtil

install:
    - cpanm --verbose --notest --configure-args="--no-ed25519" .

script:
    - prove -bl $(test-files)
