dist: bionic

env:
- TEST_WITH_NETWORK=1

language: perl
perl:
    - "5.28"
    - "5.26"
    - "5.24"
    - "5.22"

before_install:
    - eval $(curl https://travis-perl.github.io/init)
    - sudo apt-get install -y libidn11-dev libldns-dev
    - cpan-install --deps Devel::CheckLib Module::Install Module::Install::XSUtil

install:
    # --no-internal-ldns is faster
    # --no-ed25519 is compatibile with the openssl we get
    - cpanm --verbose --notest --configure-args="--no-ed25519 --no-internal-ldns" .

script:
    - prove -bl $(test-files)
