dist: focal

env:
- TEST_WITH_NETWORK=1

language: perl
perl:
    - "5.38"
    - "5.34"
    - "5.30.2"

before_install:
      # quoting preserves newlines in the script and then avoid error if the
      # script contains comments
    - eval "$(curl https://travis-perl.github.io/init)"
    - sudo apt-get install -y libidn2-dev
    - cpan-install --deps Devel::CheckLib Module::Install Module::Install::XSUtil

install:
    - cpanm --verbose --notest --configure-args="--no-ed25519" .

script:
    - prove -bl $(test-files)
